networks:
  officenet:
    external: true
services:
  app:
    image: 'rohmanahmad/php8.3-apache-full:latest'
    container_name: codeigniter_dev
    stdin_open: true
    tty: true
    networks:
      - officenet
    ports:
      - 3000:80
      - 3001:3001
      - 3002:3002
    volumes:
      - ./src:/var/www/html
      - ./apache/ports.conf:/etc/apache2/ports.conf
      - ./apache/vhosts/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache/vhosts/app1.conf:/etc/apache2/sites-enabled/app1.conf
      - ./apache/vhosts/app2.conf:/etc/apache2/sites-enabled/app2.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - USE_ZEND_ALLOC=0
    working_dir: /var/www/html
